services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db


  alembic:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app
    working_dir: /app
    entrypoint: [ "alembic" ]


volumes:
  postgres_data: